###
POST http://localhost:8080/v1/devices/book/Samsung/GalaxyS8/Edson

###
POST http://localhost:8080/v1/devices/return/Samsung/GalaxyS8

###
GET http://localhost:8080/v1/devices

###
GET http://localhost:8070/v1/getdevice/Samsung/GalaxyS8
